#spring:
#  application:
#    name: spring-cloud-service-demo
#
#server:
#  port: 8765
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8763/eureka/